on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  restart-inference:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Restart inference via E2E API
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo "Restarting inference after merge..."

          URL="https://api.e2enetworks.com/myaccount/api/v1/gpu/github-inferences/restart/"\
          "?apikey=${API_KEY}"

          curl --fail --show-error -X PUT "$URL" \
            -H "Authorization: Bearer ${AUTH_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "inference_uuids": [
                "b137de60-5a20-4282-bab3-be556eb0a9c7",
                "76c51dc3-f3ec-448b-943c-7396c4fcc553i"
              ]
            }'
